version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: nucleus-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: nucleus_lab
      MYSQL_USER: nucleus_user
      MYSQL_PASSWORD: nucleus_pw
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  flyway:
    image: flyway/flyway:latest
    depends_on:
      - db
    environment:
      FLYWAY_LOCATIONS: filesystem:/flyway/sql,filesystem:/flyway/seed
      FLYWAY_URL: jdbc:mysql://db:3306/nucleus_lab?allowPublicKeyRetrieval=true&useSSL=false
      FLYWAY_USER: nucleus_user
      FLYWAY_PASSWORD: nucleus_pw
      FLYWAY_SCHEMAS: nucleus_lab
      FLYWAY_TABLE: schema_version
      FLYWAY_CLEAN_DISABLED: 'false'
    volumes:
      - ./migrations:/flyway/sql
      - ./seed:/flyway/seed

volumes:
  db_data:
