version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: nucleus-mysql
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  flyway:
    image: flyway/flyway:latest
    depends_on:
      - db
    env_file:
      - .env
    environment:
      FLYWAY_LOCATIONS:            filesystem:/flyway/sql,filesystem:/flyway/seed
      FLYWAY_URL:                  jdbc:mysql://db:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
      FLYWAY_USER:                 ${DB_USER}
      FLYWAY_PASSWORD:             ${DB_PASS}
      FLYWAY_SCHEMAS:              ${DB_NAME}
      FLYWAY_TABLE:                schema_version
      FLYWAY_CLEAN_DISABLED:       'false'
      FLYWAY_BASELINE_ON_MIGRATE:  'true'
    volumes:
      - ./migrations:/flyway/sql
      - ./seed:/flyway/seed

volumes:
  db_data:
